### ISSUE TITLE
Evaluate SBC with 500 samples

### ISSUE THREAD

**Issue by neelsura12** [neelsura12/gsoc#3]
Here: target is pdf of LambertW x Fx

[sbc_delta_sean_variation_500_samples.pdf](https://github.com/neelsura12/gsoc/files/6842923/sbc_delta_sean_variation_500_samples.pdf)
[sbc_sigma_sean_variation_500_samples.pdf](https://github.com/neelsura12/gsoc/files/6842924/sbc_sigma_sean_variation_500_samples.pdf)
[sbc_mu_sean_variation_500_samples.pdf](https://github.com/neelsura12/gsoc/files/6842925/sbc_mu_sean_variation_500_samples.pdf)

Delta comes up low, sigma comes up high, mu comes in just right.

@spinkney

**Comment by neelsura12** [comment]
Here: target is likelihood of LambertW x Fx

[sbc_delta_orig_mle.pdf](https://github.com/neelsura12/gsoc/files/6843113/sbc_delta_orig_mle.pdf)
[sbc_sigma_orig_mle.pdf](https://github.com/neelsura12/gsoc/files/6843112/sbc_sigma_orig_mle.pdf)
[sbc_mu_orig_mle.pdf](https://github.com/neelsura12/gsoc/files/6843111/sbc_mu_orig_mle.pdf)

Relative to above-
Mu looks worse, but still uniform-ish.
Sigma comes in low (opposite of above; this is due to invgamma prior vs. gamma prior). 
Delta looks better.

The prior is affecting Sigma's SBC quite a bit. Going to try normal(0, 10).

**Comment by neelsura12** [comment]
Here: target is likelihood of LambertW x Fx with sigma ~ normal(0, sqrt(pi/2))

[sbc_delta_normal_prior_on_sigma.pdf](https://github.com/neelsura12/gsoc/files/6843370/sbc_delta_normal_prior_on_sigma.pdf)
[sbc_sigma_normal_prior_on_sigma.pdf](https://github.com/neelsura12/gsoc/files/6843372/sbc_sigma_normal_prior_on_sigma.pdf)
[sbc_mu_normal_prior_on_mu.pdf](https://github.com/neelsura12/gsoc/files/6843371/sbc_mu_normal_prior_on_mu.pdf)

This looks the best so far. Replacing the prior density (invgamma/gamma -> half-normal) seems to help inference on sigma. For completeness, I'm running sean's version (the pdf) with a better prior on sigma.

EDIT: Removed the word "fixing" as it had a misleading meaning in this context.

**Comment by neelsura12** [comment]
Here: target is pdf of LambertW x Fx with sigma ~ normal(0, sqrt(pi/2))

[sbc_delta_with_pdf_and_normal_sigma_prior.pdf](https://github.com/neelsura12/gsoc/files/6843563/sbc_delta_with_pdf_and_normal_sigma_prior.pdf)
[sbc_sigma_with_pdf_and_normal_sigma_prior.pdf](https://github.com/neelsura12/gsoc/files/6843566/sbc_sigma_with_pdf_and_normal_sigma_prior.pdf)
[sbc_mu_with_pdf_and_normal_sigma_prior.pdf](https://github.com/neelsura12/gsoc/files/6843565/sbc_mu_with_pdf_and_normal_sigma_prior.pdf)

This looks about the same. Changing the prior density on sigma helps both inferences.

EDIT: Removed the word "fixing" as it had a misleading meaning in this context.

**Comment by spinkney** [comment]
When you say fixing the prior you mean that mu and sigma are input as data? 

Something I've wondered, and brought up today, is that the mu/sigma as params needs some additional adjustment. Or we just try with the sample mean/sd

**Comment by neelsura12** [comment]
Hey, I updated my comments with the additional warning "EDIT", the word "fixing" above does not mu/sigma are fixed, mu has a normal(0,1) prior and sigma has either invgamma/gamma/half-normal prior. It seems SBC is returning a histogram that looks like the prior density when we do sigma ~ invgamma/gamma.

**Comment by neelsura12** [comment]
From [this](https://betanalpha.github.io/assets/case_studies/principled_bayesian_workflow.html#ref-TaltsEtAl:2018) post, 
"To use simulation-based calibration with Markov chain Monte Carlo we have to first thin our Markov chains to remove any effective autocorrelation."

For the explicit model with thinned samples, SBC looks good (uniform)
[sbc_sigma_explicit.pdf](https://github.com/neelsura12/gsoc/files/6886542/sbc_sigma_explicit.pdf)
[sbc_mu_explicit.pdf](https://github.com/neelsura12/gsoc/files/6886543/sbc_mu_explicit.pdf)
[sbc_delta_explicit.pdf](https://github.com/neelsura12/gsoc/files/6886544/sbc_delta_explicit.pdf)
